export const VERSION = '2.1.0';

export type {
  DailyUsage,
  ModelBreakdown,
  CachePricingDetails,
  ProviderData,
  ProviderColors,
  AggregatedStats,
  DayOfWeekEntry,
  TopModelEntry,
  UsageEvent,
  InputOutputMetrics,
  MonthlyBurnMetrics,
  CacheEconomics,
  ModelEfficiencyEntry,
  ModelEfficiencyMetrics,
  CacheRoiSummary,
  CacheRoiBreakdown,
  CacheRoiMetrics,
  HourOfDayEntry,
  SessionSummary,
  ProjectSummary,
  SessionMetrics,
  SessionDrilldownEntry,
  ProjectDrilldownEntry,
  AttributionWindow,
  AttributionTaskStyle,
  AttributionCluster,
  ExplainEvidenceRow,
  ExplainAnomaly,
  ExplainReport,
  FocusEntry,
  FocusReport,
  FlowBlockLabel,
  FlowBlock,
  TokenVelocityPoint,
  ReplayDaySummary,
  ReplayReport,
  NutritionOutcomeSignal,
  NutritionRepoSummary,
  NutritionReport,
  ModelMixShiftEntry,
  CompareMore,
  MoreStats,
  ProviderResult,
  TokenleakOutput,
  RenderOptions,
  DateRange,
  CompareOutput,
  CompareDeltas,
} from './types';

export {
  DEFAULT_DAYS,
  DEFAULT_CONCURRENCY,
  MAX_JSONL_RECORD_BYTES,
  SCHEMA_VERSION,
} from './constants';

export {
  calculateStreaks,
  rollingWindow,
  findPeakDay,
  dayOfWeekBreakdown,
  cacheHitRate,
  calculateAverages,
  topModels,
  aggregate,
  mergeProviderData,
  compareRanges,
  computeDeltas,
  buildCompareOutput,
  parseCompareRange,
  computePreviousPeriod,
  buildMoreStats,
  buildFocusReport,
  computeModelMixShift,
  buildExplainReport,
  buildReplayReport,
  buildNutritionReport,
} from './aggregation';

export {
  buildSessionRollups,
  buildProjectRollups,
  buildAttributionClusters,
  inferRepoRoot,
  inferDirectoryLabel,
  normalizeScores,
} from './aggregation/analytics';

export {
  ONE_DAY_MS,
  dateToUtcMs,
  formatDateStringUtc,
  compareDateStrings,
} from './date-utils';

export { analyzeEfficiency, DOWNGRADE_PATHS, getDowngradePath } from './advisor';
export type { AdvisorRecommendation, AdvisorReport, AdvisorModelPricing } from './advisor';
