export const VERSION = '2.1.0';

export type {
  DailyUsage,
  ModelBreakdown,
  CachePricingDetails,
  ProviderData,
  ProviderColors,
  ProviderWarning,
  AggregatedStats,
  DayOfWeekEntry,
  TopModelEntry,
  UsageEvent,
  InputOutputMetrics,
  MonthlyBurnMetrics,
  CacheEconomics,
  ModelEfficiencyEntry,
  ModelEfficiencyMetrics,
  CacheRoiSummary,
  CacheRoiBreakdown,
  CacheRoiMetrics,
  HourOfDayEntry,
  SessionSummary,
  ProjectSummary,
  SessionMetrics,
  SessionDrilldownEntry,
  ProjectDrilldownEntry,
  AttributionWindow,
  AttributionTaskStyle,
  AttributionCluster,
  ExplainEvidenceRow,
  ExplainAnomaly,
  ExplainReport,
  FocusEntry,
  FocusReport,
  FlowBlockLabel,
  FlowBlock,
  TokenVelocityPoint,
  ReplayDaySummary,
  ReplayReport,
  CommonsPrivacyBlock,
  CommonsBucketEntry,
  CommonsProviderModelEntry,
  CommonsExport,
  CommonsInspectReport,
  WasteCategory,
  WasteRecipe,
  WasteFinding,
  WasteReport,
  NutritionOutcomeSignal,
  NutritionRepoSummary,
  NutritionReport,
  ModelMixShiftEntry,
  CompareMore,
  MoreStats,
  ProviderResult,
  TokenleakOutput,
  RenderOptions,
  DateRange,
  CompareOutput,
  CompareDeltas,
  ProviderWarningKind,
  CostSource,
  CostCompleteness,
} from './types';

export {
  DEFAULT_DAYS,
  DEFAULT_CONCURRENCY,
  MAX_JSONL_RECORD_BYTES,
  SCHEMA_VERSION,
} from './constants';

export {
  calculateStreaks,
  rollingWindow,
  findPeakDay,
  dayOfWeekBreakdown,
  cacheHitRate,
  calculateAverages,
  topModels,
  aggregate,
  mergeProviderData,
  compareRanges,
  computeDeltas,
  buildCompareOutput,
  parseCompareRange,
  computePreviousPeriod,
  buildMoreStats,
  buildFocusReport,
  computeModelMixShift,
  buildExplainReport,
  buildReplayReport,
  buildCommonsExport,
  buildCommonsPromptExport,
  inspectCommonsExport,
  buildWasteReport,
  buildNutritionReport,
  collectGitOutcomeSignals,
  clusterPrompts,
  tokenBigrams,
  buildReceipt,
  CATEGORY_LABELS,
  CATEGORY_LABELS_SHORT,
  formatReceiptDollars,
} from './aggregation';

export type {
  PromptCluster,
  ClusterOptions,
  Receipt,
  ReceiptLine,
  ReceiptSummary,
  ReceiptCategory,
  BuildReceiptOptions,
} from './aggregation';

export {
  buildSessionRollups,
  buildProjectRollups,
  buildAttributionClusters,
  inferRepoRoot,
  inferDirectoryLabel,
  normalizeScores,
} from './aggregation/analytics';

export {
  ONE_DAY_MS,
  dateToUtcMs,
  formatDateStringUtc,
  formatDateStringLocal,
  getTodayLocal,
  shiftDateStringLocal,
  inclusiveDaySpan,
  compareDateStrings,
} from './date-utils';

export {
  buildDailyCostCompleteness,
  buildEventCostCompleteness,
  mergeCostCompleteness,
} from './cost-completeness';

export { analyzeEfficiency, DOWNGRADE_PATHS, getDowngradePath } from './advisor';
export type { AdvisorRecommendation, AdvisorReport, AdvisorModelPricing } from './advisor';
